# This is a basic workflow to help you get started with Actions

name: Automated Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build the solution (Debug)
        run: msbuild ManagedWinapi-2010-4.8.1.sln /property:Configuration=Debug
      
      - name: Build the solution (ReleaseSigned)
        run: msbuild ManagedWinapi-2010-4.8.1.sln /property:Configuration=ReleaseSigned

      - name: Upload artifact bin_Debug
        uses: actions/upload-artifact@v4
        with:
            name: bin_Debug
            path: ManagedWinapi\bin\Debug\
            
      - name: Upload artifact bin_ReleaseSigned
        uses: actions/upload-artifact@v4
        with:
            name: bin_ReleaseSigned
            path: ManagedWinapi\bin\ReleaseSigned\
